// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6fd_3QV8aAGjvd7wlaN6u3blVksBAQJw',
    appId: '1:826926313104:web:63674ba1a6443983ca3215',
    messagingSenderId: '826926313104',
    projectId: 'moodtunes-86b30',
    authDomain: 'moodtunes-86b30.firebaseapp.com',
    storageBucket: 'moodtunes-86b30.firebasestorage.app',
    measurementId: 'G-88J9FPJ1PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBRb3AkaErawze_tamiHI4_Ws2UVzVmE8',
    appId: '1:826926313104:android:5a20584ec3f534c5ca3215',
    messagingSenderId: '826926313104',
    projectId: 'moodtunes-86b30',
    storageBucket: 'moodtunes-86b30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCsFKUZ2KRBNl6RWFUBr-ifDJtoKPvLqQ',
    appId: '1:826926313104:ios:b3e3c6aaa552f93aca3215',
    messagingSenderId: '826926313104',
    projectId: 'moodtunes-86b30',
    storageBucket: 'moodtunes-86b30.firebasestorage.app',
    iosBundleId: 'com.example.moodtunes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCsFKUZ2KRBNl6RWFUBr-ifDJtoKPvLqQ',
    appId: '1:826926313104:ios:b3e3c6aaa552f93aca3215',
    messagingSenderId: '826926313104',
    projectId: 'moodtunes-86b30',
    storageBucket: 'moodtunes-86b30.firebasestorage.app',
    iosBundleId: 'com.example.moodtunes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6fd_3QV8aAGjvd7wlaN6u3blVksBAQJw',
    appId: '1:826926313104:web:aedf4e7606b37e33ca3215',
    messagingSenderId: '826926313104',
    projectId: 'moodtunes-86b30',
    authDomain: 'moodtunes-86b30.firebaseapp.com',
    storageBucket: 'moodtunes-86b30.firebasestorage.app',
    measurementId: 'G-CZC2YVZVXB',
  );
}
