function Toys() {
    function m4() {
      alert("I like to play with Toys,My favourite Toy is Teddy Bear")
    }
    return (
      <>
       <button onClick={m4}>So What you think about Toys?</button>
        </>
    );
  }export default Toys  2333333q1``````````````````````````````````````````````````````````````````````````````````````````````````                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ;